name: Build Test Front-end

on:
  push

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Using Node 16
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
    - name: npm ci
      working-directory: ./front-end
      run: npm ci
    - name: npm run build
      working-directory: ./front-end
      run: npm run build
