name: Build Test Back-end

on:
  push:
    branches:
      - '*'         # matches every branch that doesn't contain a '/'
      - '*/*'       # matches every branch containing a single '/'
      - '**'        # matches every branch
      - '!master'   # excludes master
      - '!release'   # excludes release

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Using Node 16
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
    - name: npm ci
      working-directory: ./back-end
      run: npm ci
    - name: npm run build
      working-directory: ./back-end
      run: npm run build
