name: Automatic pull from github
on:
  push:
    branches:
      - release
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Pull from github
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            whoami
            cd ~/ft_transcendence
            git pull origin release
            docker container prune -f
            docker image prune -f
            docker-compose up --build -d
